inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rake.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.4.5

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma
