default:
  browser: chrome
  headless: false
  screenshots_on_failure: true
  downloads_dir: "./downloads"
  viewport:
    width: 1920
    height: 1080

local:
      browser: chrome
      headless: false
      screenshots_on_failure: true
      downloads_dir: "./downloads"
      viewport:
        width: 1920
        height: 1080

ci:
  browser: chrome
  headless: true
  screenshots_on_failure: true
  downloads_dir: "./downloads"
  viewport:
    width: 1920
    height: 1080