default:
  browser: chrome
  # browser: firefox
  # browser: safari
  # browser: edge
  # browser: headless_chrome
  window_width: 1920
  window_height: 1080
  max_wait_time: 5

local:
  browser: chrome
  window_width: 1920
  window_height: 1080
  max_wait_time: 5

ci:
  browser: headless_chrome
  window_width: 1920
  window_height: 1080
  max_wait_time: 5

